# docker-compose.yml
version: '3.8'
services:
  postgres:
    image: postgres:latest
    volumes:
     - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"


  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.1
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    depends_on:
      - zookeeper

  web:
    image: nginx:latest
    container_name: web_server
    ports:
      - "8080:8000"
    volumes:
      - ./web:/usr/share/nginx/html
    depends_on:
      - kafka
      - zookeeper

  app:
    build: .
    container_name: app_service
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      DATABASE_URL: postgresql://username:password@postgres:5432/dbname
    depends_on:
      - kafka
      - zookeeper
      - postgres
    networks:
      - default
volumes:
  postgres_data:

networks:
  default:
    name: kafka_network