version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: local
      POSTGRES_DB: taskmanager
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: local

  web:
    build: .
    depends_on:
      - db
      - rabbitmq
    environment:
      DATABASE_URL: "postgresql://postgres:local@db:localhost/taskmanager"
      RABBITMQ_URL: "amqp://rabbitmq:local@rabbitmq:5672"
    ports:
      - "8000:8000"
    command: python manage.py runserver
